### ISSUE TITLE
Warehouse is not targeted here

### ISSUE THREAD

**Issue by barberscott** [mikegfuller/dbt-smorgasbord#19]
If a credential is rotated and you do not specify the warehouse, it will be nulled out and revert to the warehouse set at the connection level in the project.

https://github.com/mikegfuller/dbt-smorgasbord/blob/f39e7ec5f75f11df1d0dbf972492877ad7d56d3e/python/rotate_keypair.py#L46-L60

**Comment by mikegfuller** [comment]
@barberscott thanks for raising - opened PR #20 which passed my tests but would love to get your eyes on it before merging
